import { PREVIEW_ORGANIZATION } from './documents.constants';

/**
 * Jeu de données de prévisualisation (US-00-08, servi par la phase H). Un administrateur doit
 * pouvoir juger son gabarit **avant** de le publier : cette fixture couvre les cas qui cassent
 * une mise en page — deux lignes d'abonnement dont une avec sous-titre, deux postes de frais,
 * une remise, la clause d'essai et les quatre années du pluriannuel.
 *
 * Elle ne touche à aucune donnée réelle : c'est un devis qui n'existe pas.
 */
export function previewQuoteData(): Record<string, unknown> {
  return {
    emetteur_nom: 'Votre société',
    emetteur_adresse: '1 rue de l’Exemple, 75000 Paris',
    mairie_prefixe: 'Commune de ',
    mairie_prefixe_min: 'commune de ',
    mairie_nom: PREVIEW_ORGANIZATION,
    mairie_habitants: '9 820',
    strate: '5 000-9 999',
    mairie_adresse: '1 place de la Mairie',
    mairie_cp_ville: '00000 Exempleville',
    mairie_siret: '00000000000000',
    contact_nom: 'Prénom Nom',
    contact_fonction: 'Commercial',
    contact_email: 'commercial@exemple.fr',
    signataire_periscolia: 'Signataire',
    ref_devis: 'DEV-0000-000-XX000',
    date_emission: '1 janvier 2026',
    date_validite: '31 janvier 2026',
    date_demarrage: '1 février 2026',
    date_signature: '',
    engagement_txt: '36 mois',
    resiliation_txt: 'Sans résiliation anticipée, préavis de 2 mois',
    conditions_txt: '',
    clause_essai: true,
    formule: 'CONFORT',
    abo_ht_affiche: '170,55',
    offre_items: [{ texte: 'Exemple d’argument commercial' }],
    lignes_abo: [
      { nom: 'Abonnement CONFORT', sous: 'Base année civile', qte: '1', pu: '189,50', remise: '10 %', total: '170,55' },
      { nom: 'Option', sous: '', qte: '3', pu: '12,00', remise: '—', total: '36,00' },
    ],
    lignes_frais: [
      { nom: 'Déploiement', qte: '1', pu: '500,00', remise: '—', total: '500,00' },
      { nom: 'Formation', qte: '1', pu: '1 250,00', remise: '—', total: '1 250,00' },
    ],
    has_remise: true,
    remise_titre: 'Remise commerciale',
    remise_sous: 'Sur l’abonnement mensuel',
    remise_badge: '-10 %',
    remise_valeur: '18,95',
    mention_abo: 'Montant après remise de 10 %',
    total_ht_abo: '206,55',
    total_tva_abo: '41,31',
    total_ttc_abo: '247,86',
    total_ht_frais: '1 750,00',
    total_tva_frais: '350,00',
    total_ttc_frais: '2 100,00',
    py_annee1: '2026',
    py_annee2: '2027',
    py_annee3: '2028',
    py_annee4: '2029',
    py_frais_1: '500,00',
    py_frais_2: '—',
    py_frais_3: '—',
    py_frais_4: '—',
    py_formation_1: '1 250,00',
    py_formation_2: '—',
    py_formation_3: '—',
    py_formation_4: '—',
    py_materiel_1: '—',
    py_materiel_2: '—',
    py_materiel_3: '—',
    py_materiel_4: '—',
    py_abo_1: '1 879,05',
    py_abo_1_detail: ' (11 mois)',
    py_abo_note: '',
    py_abo_2: '2 478,60',
    py_abo_3: '2 478,60',
    py_abo_4: '2 478,60',
    py_total_ht_1: '3 629,05',
    py_total_ht_2: '2 478,60',
    py_total_ht_3: '2 478,60',
    py_total_ht_4: '2 478,60',
    py_total_ttc_1: '4 354,86',
    py_total_ttc_2: '2 974,32',
    py_total_ttc_3: '2 974,32',
    py_total_ttc_4: '2 974,32',
    // Le cachet réel du projet est injecté par le service : la fixture ne le porte pas.
    signature_image: '',
  };
}
